"""
enrich_data.py — Enrich the frontend JSON data files for the iDISC HUD.

Reads the EXISTING translators.json + clients.json (previously generated by extract_data.py)
and enriches them with constraint data from the 4 backend reference CSVs:

  - DATA/Processed/Translators_Data.csv  → rolling metrics, assignment status
  - DATA/Clients.csv                     → selling price, min quality, wildcard
  - DATA/Schedules.csv                   → work schedules (shift times + weekdays)
  - DATA/TranslatorsCost+Pairs.csv       → per-pair hourly rates

Usage:
    python frontend/enrich_data.py
"""

import pandas as pd
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(SCRIPT_DIR, "..")
DATA_DIR = os.path.join(ROOT_DIR, "DATA")
OUT_DIR = os.path.join(SCRIPT_DIR, "data")
os.makedirs(OUT_DIR, exist_ok=True)

# ── Load existing JSON files ─────────────────────────────────────────────────

TRANSLATORS_JSON = os.path.join(OUT_DIR, "translators.json")
CLIENTS_JSON = os.path.join(OUT_DIR, "clients.json")

# ── Load backend reference CSVs ──────────────────────────────────────────────

TRANSLATORS_DATA_CSV = os.path.join(DATA_DIR, "Processed", "Translators_Data.csv")
CLIENTS_CSV = os.path.join(DATA_DIR, "Clients.csv")
SCHEDULES_CSV = os.path.join(DATA_DIR, "Schedules.csv")
PAIRS_CSV = os.path.join(DATA_DIR, "TranslatorsCost+Pairs.csv")

print("=" * 60)
print("  iDISC Data Enricher — Constraint-Aware JSON Generation")
print("=" * 60)

# 1. Load existing JSON files
print(f"\n[1/6] Loading existing translators.json ...")
with open(TRANSLATORS_JSON, "r", encoding="utf-8") as f:
    translators = json.load(f)
print(f"       {len(translators)} translators loaded.")

print(f"[2/6] Loading existing clients.json ...")
with open(CLIENTS_JSON, "r", encoding="utf-8") as f:
    clients = json.load(f)
print(f"       {len(clients)} clients loaded.")

# 2. Translators_Data.csv (comma-separated, generated by preprocessing pipeline)
print(f"[3/6] Loading Translators_Data.csv ...")
tr_data = pd.read_csv(TRANSLATORS_DATA_CSV)
tr_data["TRANSLATOR"] = tr_data["TRANSLATOR"].str.strip()
print(f"       {len(tr_data)} translators with rolling metrics.")

# 3. Clients.csv (semicolon-separated, comma decimals)
print(f"[4/6] Loading Clients.csv ...")
clients_ref = pd.read_csv(CLIENTS_CSV, sep=";", decimal=",", encoding="utf-8")
clients_ref.columns = [c.strip() for c in clients_ref.columns]
clients_ref = clients_ref.loc[:, ~clients_ref.columns.str.startswith("Unnamed")]
print(f"       {len(clients_ref)} clients with constraint data.")

# 4. Schedules.csv (semicolon-separated)
print(f"[5/6] Loading Schedules.csv ...")
schedules = pd.read_csv(SCHEDULES_CSV, sep=";", decimal=",", encoding="utf-8")
schedules.columns = [c.strip() for c in schedules.columns]
schedules["NAME"] = schedules["NAME"].str.strip()
print(f"       {len(schedules)} schedule entries.")

# 5. TranslatorsCost+Pairs.csv (semicolon-separated, comma decimals)
print(f"[6/6] Loading TranslatorsCost+Pairs.csv ...")
pairs_df = pd.read_csv(PAIRS_CSV, sep=";", decimal=",", encoding="utf-8")
pairs_df.columns = [c.strip() for c in pairs_df.columns]
pairs_df["TRANSLATOR"] = pairs_df["TRANSLATOR"].str.strip()
pairs_df["SOURCE_LANG"] = pairs_df["SOURCE_LANG"].str.strip()
pairs_df["TARGET_LANG"] = pairs_df["TARGET_LANG"].str.strip()
pairs_df["HOURLY_RATE"] = pd.to_numeric(pairs_df["HOURLY_RATE"], errors="coerce")
print(f"       {len(pairs_df)} translator-pair rate entries.")

# ── Build lookup tables ──────────────────────────────────────────────────────

# Translators_Data lookup: name -> rolling metrics row
tr_data_lookup = tr_data.set_index("TRANSLATOR").to_dict(orient="index")

# Schedules lookup: name -> schedule info
schedule_lookup = {}
for _, row in schedules.iterrows():
    name = str(row["NAME"]).strip()
    days = []
    for day_col in ["MON", "TUES", "WED", "THURS", "FRI", "SAT", "SUN"]:
        if int(row.get(day_col, 0)) == 1:
            days.append(day_col)
    schedule_lookup[name] = {
        "start": str(row.get("START", "")).strip(),
        "end": str(row.get("END", "")).strip(),
        "days": days,
    }

# Pairs lookup: translator -> dict of {pair_key: rate}
pairs_lookup = {}
for _, row in pairs_df.iterrows():
    name = str(row["TRANSLATOR"]).strip()
    if name not in pairs_lookup:
        pairs_lookup[name] = {}
    pair_key = f"{row['SOURCE_LANG']}->{row['TARGET_LANG']}"
    rate = row["HOURLY_RATE"]
    if pd.notna(rate):
        pairs_lookup[name][pair_key] = round(float(rate), 2)

# Clients.csv lookup: CLIENT_NAME -> {SELLING_HOURLY_PRICE, MIN_QUALITY, WILDCARD}
clients_constraint_lookup = {}
for _, row in clients_ref.iterrows():
    name = str(row.get("CLIENT_NAME", "")).strip()
    if name:
        shp = row.get("SELLING_HOURLY_PRICE")
        mq = row.get("MIN_QUALITY")
        wc = row.get("WILDCARD")
        clients_constraint_lookup[name] = {
            "sellingHourlyPrice": round(float(shp), 2) if pd.notna(shp) else None,
            "minQuality": round(float(mq), 2) if pd.notna(mq) else None,
            "wildcard": str(wc).strip() if pd.notna(wc) and str(wc).strip() else None,
        }

# ── ENRICH TRANSLATORS ───────────────────────────────────────────────────────
print("\n-- Enriching translators.json --")

enriched_count = 0
schedule_count = 0
rates_count = 0

for entry in translators:
    name = entry["name"]

    # ── Enrich from Translators_Data.csv (rolling metrics + flags) ──
    metrics = tr_data_lookup.get(name, {})
    entry["rollingQualityEma"] = round(float(metrics.get("rolling_quality_ema", entry.get("quality", 5.0))), 3)
    entry["rollingPunctuality"] = round(float(metrics.get("rolling_punctuality_score", 0.5)), 4)
    entry["rollingEfficiency"] = round(float(metrics.get("rolling_efficiency_ratio", 1.0)), 4)
    entry["rollingAvgTaskTime"] = round(float(metrics.get("rolling_avg_task_time", 0)), 3)
    entry["domainExperience"] = int(metrics.get("domain_experience", 0))
    entry["taskTypeExperience"] = int(metrics.get("task_type_experience", 0))
    entry["isNewEmployee"] = int(metrics.get("IS_NEW_EMPLOYEE", 0))
    entry["isSpecialist"] = int(metrics.get("IS_SPECIALIST", 0))
    entry["assigned"] = int(metrics.get("assigned", 0))
    entry["rollingTaskCount"] = int(metrics.get("rolling_task_count", 0))

    if metrics:
        enriched_count += 1

    # ── Enrich from Schedules.csv ──
    sched = schedule_lookup.get(name, None)
    entry["schedule"] = sched
    if sched:
        schedule_count += 1

    # ── Enrich from TranslatorsCost+Pairs.csv (per-pair rates) ──
    pair_rates = pairs_lookup.get(name, {})
    entry["hourlyRates"] = pair_rates
    if pair_rates:
        rates_count += 1

out_path = os.path.join(OUT_DIR, "translators.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(translators, f, ensure_ascii=False, indent=None)
print(f"  {len(translators)} translators -> {out_path}")
print(f"  {enriched_count} enriched with rolling metrics")
print(f"  {schedule_count} with schedule data")
print(f"  {rates_count} with per-pair hourly rates")

# ── ENRICH CLIENTS ───────────────────────────────────────────────────────────
print("\n-- Enriching clients.json --")

constraints_found = 0
for entry in clients:
    name = entry["name"]

    # ── Enrich from Clients.csv (constraint fields) ──
    constraints = clients_constraint_lookup.get(name, {})
    entry["sellingHourlyPrice"] = constraints.get("sellingHourlyPrice")
    entry["minQuality"] = constraints.get("minQuality")
    entry["wildcard"] = constraints.get("wildcard")

    if constraints:
        constraints_found += 1

out_path = os.path.join(OUT_DIR, "clients.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(clients, f, ensure_ascii=False, indent=None)
print(f"  {len(clients)} clients -> {out_path}")
print(f"  {constraints_found} enriched with constraint data")

print("\nDone! Enriched JSON files saved to frontend/data/")
